### ISSUE TITLE
Builds succeed but create unusable libraries when mustach built with jsonc only.

### ISSUE THREAD

**Issue by TreyBoudreau** [RekGRpth/pg_mustach#1]
If one builds and installs `mustach` with `jsonc` only, builds of `pg_mustach` generate the following warnings:

> mustach-cjson.c: In function ‘mustach_process_cjson’:
> mustach-cjson.c:22:12: warning: implicit declaration of function ‘MUSTACH_ERROR_USER’ [-Wimplicit-function-declaration]
>    22 |     return MUSTACH_ERROR_USER(1);

The library continues to build, but generates a `.so` that fails to load because of the missing `MUSTACH_ERROR_USER` function:
> ERROR:  could not load library "/usr/lib/postgresql/16/lib/pg_mustach.so": /usr/lib/postgresql/16/lib/pg_mustach.so: undefined symbol: MUSTACH_ERROR_USER

**Comment by RekGRpth** [comment]
I think You are using very old mustach library that hasn't [MUSTACH_ERROR_USER](https://github.com/RekGRpth/mustach/commit/abee5216f02b69d5fc6fa4c2f3ec287803eeadc6#diff-6a4eb9ca253ba837ac896d6db7b8c7f913a89128ddbdae98651af1cfd58e6f61R144) macro, try use latest one

**Comment by TreyBoudreau** [comment]
I have the very tip of the `mustach` GitLab `master` branch. It happens because on the `#else` side of the header checks in `mustach-cjson.c`, `mustach-jansson.c`, and `mustach-json-c.c` the code references `MUSTACH_ERROR_USER` but doesn't include any `mustach` headers. I fixed it locally like this:

```
#else
#include "mustach/mustach.h"

int mustach_process_cjson(const char *template, size_t length, const char *value, size_t buffer_length, int flags, FILE *file, char **err) {
    *err = "!mustach_cjson";
    fclose(file);
    return MUSTACH_ERROR_USER(1);
}
#endif
```
This works, but as a `mustach` newbie I don't know if the fix should include `mustach.h`, or `mini-mustach.h` where we actually find the definition.

**Comment by RekGRpth** [comment]
fixed by https://github.com/RekGRpth/pg_mustach/commit/65583427a0d8a4d723f63a2af8d9ef74b9f18dac, thanx
